# Generated by Django 5.1.2 on 2024-12-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformuser",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
