# Generated by Django 5.1.2 on 2024-11-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleeper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleeperleague",
            name="name",
            field=models.CharField(
                help_text="Year e.g. 2018, 2019, 2020, etc.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sleeperleague",
            name="season",
            field=models.CharField(help_text="nfl", max_length=50),
        ),
        migrations.AlterField(
            model_name="sleeperleague",
            name="sport",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="SleeperLeagueRulebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the rulebook", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A description of the rulebook", null=True
                    ),
                ),
                (
                    "league",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebook",
                        to="sleeper.sleeperleague",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SleeperRulebookRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_title",
                    models.CharField(help_text="Title of the rule", max_length=200),
                ),
                (
                    "rule_description",
                    models.TextField(help_text="Detailed description of the rule"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ordering",
                    models.IntegerField(
                        default=0, help_text="Order of the rule within the rulebook"
                    ),
                ),
                (
                    "rulebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="sleeper.sleeperleaguerulebook",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="SleeperRulebookRuleSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subsection_title",
                    models.CharField(
                        help_text="Title of the subsection", max_length=200
                    ),
                ),
                (
                    "subsection_content",
                    models.TextField(help_text="Content of the subsection"),
                ),
                (
                    "ordering",
                    models.IntegerField(
                        default=0, help_text="Order of the subsection within the rule"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="sleeper.sleeperrulebookrule",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.AddConstraint(
            model_name="sleeperrulebookrule",
            constraint=models.UniqueConstraint(
                fields=("rulebook", "ordering"), name="unique_ordering_within_rulebook"
            ),
        ),
        migrations.AddConstraint(
            model_name="sleeperrulebookrulesubsection",
            constraint=models.UniqueConstraint(
                fields=("rule", "ordering"), name="unique_ordering_within_rule"
            ),
        ),
    ]
